=== traintastic/lncv/xml/lncvmodule.xsd
<?xml version="1.0"?>
<!--
  License: CC-BY-4.0 <https://creativecommons.org/licenses/by/4.0/>
  GitHub: https://github.com/traintastic/lncv
  Author(s): Reinder Feenstra
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="language">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z]{2}-[a-z]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="name">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="language" type="language" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="lncvmodule">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="vendor" type="xs:string"/>
        <xs:element ref="name" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="lncv" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="name" minOccurs="1" maxOccurs="unbounded"/>
              <xs:element name="value">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="option" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="name" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="value" type="xs:unsignedShort" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="default" type="xs:unsignedShort" use="optional"/>
                  <xs:attribute name="min" type="xs:unsignedShort" use="optional"/>
                  <xs:attribute name="max" type="xs:unsignedShort" use="optional"/>
                  <xs:attribute name="gain" type="xs:double" use="optional"/>
                  <xs:attribute name="offset" type="xs:double" use="optional"/>
                  <xs:attribute name="unit" type="xs:string" use="optional"/>
                  <xs:attribute name="readonly" type="xs:boolean" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="lncv" type="xs:unsignedShort" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:unsignedShort" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== traintastic/lncv/xml/uhlenbrock-s88-loconet-adaptor-63880.xml
<?xml version="1.0" encoding="UTF-8"?>
<lncvmodule id="6388" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lncvmodule.xsd">
  <license url="https://creativecommons.org/licenses/by/4.0/">CC-BY-4.0</license>
  <source url="https://github.com/traintastic/lncv">LNCV @ GitHub</source>
  <author>Reinder Feenstra</author>
  <vendor>Uhlenbrock</vendor>
  <name language="en-us">S88 LocoNet adaptor 63880</name>
  <name language="de-de">S88 LocoNet Adapter 63880</name>
  <name language="nl-nl">S88 LocoNet adapter 63880</name>
  <lncv lncv="0">
    <name language="en-us">Module address</name>
    <name language="de-de">Moduladresse</name>
    <name language="nl-nl">Module-adres</name>
    <value default="1" min="1" max="65535"/>
  </lncv>
  <lncv lncv="1">
    <name language="en-us">Version</name>
    <name language="de-de">Version</name>
    <name language="nl-nl">Versie</name>
    <value readonly="true"/>
  </lncv>
  <lncv lncv="2">
    <name language="en-us">Startup time</name>
    <name language="de-de">Startup Zeit</name>
    <name language="nl-nl">Opstart tijd</name>
    <value default="20" max="255" gain="0.5" unit="s"/>
  </lncv>
  <lncv lncv="3">
    <name language="en-us">Number of connected S88 modules</name>
    <name language="de-de">Anzahl der angeschlossenen S88 Module</name>
    <name language="nl-nl">Aantal aangesloten S88 modules</name>
    <value default="31" min="1" max="31"/>
  </lncv>
  <lncv lncv="4">
    <name language="en-us">Base address</name>
    <name language="de-de">Basisadresse</name>
    <name language="nl-nl">Basisadres</name>
    <value default="1" min="1" max="2048"/>
  </lncv>
</lncvmodule>

=== traintastic/lncv/xml/uhlenbrock-usb-loconet-interface-63120.xml
<?xml version="1.0" encoding="UTF-8"?>
<lncvmodule id="6312" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lncvmodule.xsd">
  <license url="https://creativecommons.org/licenses/by/4.0/">CC-BY-4.0</license>
  <source url="https://github.com/traintastic/lncv">LNCV @ GitHub</source>
  <author>Reinder Feenstra</author>
  <vendor>Uhlenbrock</vendor>
  <name language="en-us">USB LocoNet interface 63120</name>
  <lncv lncv="0">
    <name language="en-us">Module address</name>
    <value default="1"/>
  </lncv>
  <lncv lncv="1">
    <name language="en-us">Software version</name>
    <value readonly="true"/>
  </lncv>
  <lncv lncv="2">
    <name language="en-us">Baudrate</name>
    <value default="4">
      <option value="1">
        <name>19200</name>
      </option>
      <option value="2">
        <name>38400</name>
      </option>
      <option value="3">
        <name>57600</name>
      </option>
      <option value="4">
        <name>115200</name>
      </option>
    </value>
  </lncv>
  <lncv lncv="4">
    <name language="en-us">LocoNet direct mode</name>
    <value default="0">
      <option value="0">
        <name language="en-us">Off</name>
      </option>
      <option value="1">
        <name language="en-us">On</name>
      </option>
    </value>
  </lncv>
</lncvmodule>

=== traintastic/lncv/xml/uhlenbrock-lissy-receiver-68610.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  License: CC-BY-4.0 <https://creativecommons.org/licenses/by/4.0/>
  GitHub: https://github.com/traintastic/lncv
  Author(s): Reinder Feenstra
-->
<lncvmodule id="6861" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lncvmodule.xsd">
  <vendor>Uhlenbrock</vendor>
  <name language="en-us">LISSY receiver 68610</name>
  <name language="de-de">LISSY Empfänger 68610</name>
  <name language="nl-nl">LISSY ontvanger 68610</name>
  <lncv lncv="0">
    <name language="en-us">Module address and first sensor address</name>
    <name language="de-de">Moduladresse und erste Sensoradresse</name>
    <name language="nl-nl">Module-adres en eerste sensor adres</name>
    <value default="1" min="1" max="4095"/>
  </lncv>
  <lncv lncv="1">
    <name language="en-us">Second sensor address</name>
    <name language="de-de">Zweite Sensoradresse</name>
    <name language="nl-nl">Tweede sensor adres</name>
    <value default="2" min="1" max="4095"/>
  </lncv>
  <lncv lncv="2">
    <name language="en-us">Function</name>
    <name language="de-de">Funktion</name>
    <name language="nl-nl">Functie</name>
    <value default="2">
      <option value="0">
        <name language="en-us">Double sensor (Reports address, category, direction and speed)</name>
        <name language="de-de">Doppelsensor (Ausgabe von Adresse, Kategorie, Fahrtrichtung und Geschwindigkeit)</name>
        <name language="nl-nl">Dubbele sensor (Meld adres, categorie, richting en snelheid)</name>
      </option>
      <option value="1">
        <name language="en-us">Two individual sensors (Reports address and category)</name>
        <name language="de-de">Zwei Einzelsensoren (Ausgabe von Adresse und Kategorie)</name>
        <name language="nl-nl">Twee onafhanklijke sensoren (Meld adres en categorie)</name>
      </option>
      <option value="2"/>
      <option value="98">
        <name language="en-us">Set all LNCVs to the value 0, except LNCV 0 and 1</name>
        <name language="de-de">Alle LNCVs auf den Wert 0 setzen, ausser LNCV 0 und 1</name>
        <name language="nl-nl">Zet alle LNCVs op de waarde 0, behalve LNCV 0 en 1</name>
      </option>
    </value>
  </lncv>
  <lncv lncv="14">
    <name language="en-us">Report locomotive speed</name>
    <name language="de-de">Ausgabe der Lokgeschwindigkeit</name>
    <name language="nl-nl">Meld locomotief snelheid</name>
    <value default="0"/>
  </lncv>
  <lncv lncv="15">
    <name language="en-us">Transfer format</name>
    <name language="de-de">Übergabeformats</name>
    <name language="nl-nl">Overdracht formaat</name>
    <value default="2">
      <option value="0">
        <name language="en-us">Disabled</name>
        <name language="de-de">Deaktiviert</name>
        <name language="nl-nl">Uitgeschakeld</name>
      </option>
      <option value="1">
        <name language="en-us">Uhlenbrock with locomotive address and category</name>
        <name language="de-de">Uhlenbrock mit Lokadresse und Kategorie</name>
        <name language="nl-nl">Uhlenbrock met lokomotief adres en categorie</name>
      </option>
      <option value="2">
        <name language="en-us">Digitrax with locomotive address and transponder exit block</name>
        <name language="de-de">Digitrax mit Lokadresse und Block frei (Transponder exit block)</name>
        <name language="nl-nl">Digitrax met locomotief adres en block vrij (Transponder exit block)</name>
      </option>
      <option value="3">
        <name language="en-us">Digitrax with locomotive address and transponder enters block</name>
        <name language="de-de">Digitrax mit Lokadresse und Block belegt (Transponder enters block)</name>
        <name language="nl-nl">Digitrax met locomotief adres en block bezet (Transponder enters block)</name>
      </option>
    </value>
  </lncv>
</lncvmodule>
